### ISSUE TITLE
SQLite: Generic error. Cannot get SourceMap info, dump raw stack:

### ISSUE THREAD

**Issue by tongwanming** [liushengyi/smartdb#12]
大佬你好，咱们smartdb 目前是否支持了 5.0.0呢。我在4.0的项目是正常的 ，在5.0 的项目报错“SQLite: Generic error. Cannot get SourceMap info, dump raw stack:”

**Comment by zhouzhuo810** [comment]
我也遇到问题了，找到原因么？ @tongwanming
