### ISSUE TITLE
怎么添加WHERE like 查询

### ISSUE THREAD

**Issue by ench2** [liushengyi/smartdb#14]
@sql.SqlQuery("select * from "+tbl+" where #{cond}")
  @sql.ReturnType([Config])
  findWhere(@sql.Param("cond") cond: string): Promise<Array<IIdPhotoModel>> {
    return sql.PromiseNull()
  }
  会在#{cond}上加了引号
${cond}好像还不支持

**Comment by liushengyi** [comment]
目前可以在外边拼接实现：

```
@sql.SqlQuery("select * from db_user where name like #{name} ")
  @sql.ReturnListType(User)
  searchUser(@sql.Param("name")name:string): Promise<Array<User>> {
    return sql.PromiseNull()
  }

  let result = await userDao.searchUser("id%")
```

**Comment by ench2** [comment]
在DBUTIL的32行加一个  ||  DbUtil.isWhere(paramValue)
   if (DbUtil.isNumber(paramValue) || DbUtil.isBool(paramValue) ||  DbUtil.isWhere(paramValue) ) 
   
   然后添加了个函数
   
  private static isWhere(entryType) {

    return typeof entryType === 'string' && entryType.split(" ")[0] == "where"
  }
  能将这个merge进去吗

**Comment by liushengyi** [comment]
不建议这样做。  我明白了你的需求，下个版本，考虑处理下。  如果你目前急用，可以自己拉下源码处理。

**Comment by liushengyi** [comment]
3.0.1版本已经发布，支持 条件拼接。

**Comment by ench2** [comment]
好的，收到，感谢
