### ISSUE TITLE
数据库是否支持加密存储？

### ISSUE THREAD

**Issue by Jsonmess** [liushengyi/smartdb#16]
防止db 文件被导出后，能直接打开，sqlite 应是支持 增加password 的吧，请问smartdb 是否支持

**Comment by liushengyi** [comment]
鸿蒙数据库本身支持数据库加密，下个版本我考虑把配置暴露出来，支持配置。
https://developer.huawei.com/consumer/cn/doc/harmonyos-guides-V5/data-encryption-V5#关系型数据库加密

**Comment by liushengyi** [comment]
3.0.2 版本已经支持。
