### ISSUE TITLE
at anonymous (oh_modules

### ISSUE THREAD

**Issue by CorvusYe** [liushengyi/smartdb#2]
你好，请问当前的仓库是不是不能用在元服务当中？

### 环境信息
![image](https://github.com/liushengyi/smartdb/assets/15630211/4ebab80f-55c4-45a8-b649-0f6f467fb59f)

### 创建过程
![image](https://github.com/liushengyi/smartdb/assets/15630211/de63d5b8-f352-4036-a5ad-b1368917a47a)

![image](https://github.com/liushengyi/smartdb/assets/15630211/51cdbbb1-3881-4c52-a337-60bc11fd5799)

### 报错信息
![image](https://github.com/liushengyi/smartdb/assets/15630211/cc988c64-74f7-414d-a383-c3f46d6a22d8)

**Comment by liushengyi** [comment]
请用模拟器或者真机测试

**Comment by CorvusYe** [comment]
模拟器上可以了，谢谢～
