### ISSUE TITLE
插入时如果参数对象某个字段数据为空，就没有办法替换对应的参数

### ISSUE THREAD

**Issue by yhyrun** [liushengyi/smartdb#23]
![image](https://github.com/user-attachments/assets/14f39d7d-6af7-4c8f-beca-75c48e9ba044)
这样判断下改就可以替换，希望修复下

**Comment by liushengyi** [comment]
你这边可以提交一个PR。

**Comment by liushengyi** [comment]
4.0.1版本已经处理该问题。

**Comment by yhyrun** [comment]
感谢作者🌹🌹



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月30日(周五) 上午10:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liushengyi/smartdb] 插入时如果参数对象某个字段数据为空，就没有办法替换对应的参数 (Issue #23)




 
4.0.1版本已经处理该问题。
