### ISSUE TITLE
数据库升级问题

### ISSUE THREAD

**Issue by Dragonloong** [liushengyi/smartdb#25]
我这边用ROOM数据库升级命令，发现升级不了，添加的属性再次执行添加方法，发现报错，您这边能提供下升级的例子和相关的代码吗

**Comment by Dragonloong** [comment]
升级前
@sql.SqlInsert('replace into db_user (id,name) values (#{id},#{name})')
  insert(@sql.Param('id') id: number, @sql.Param('name') name: string): Promise<void> {
    return sql.PromiseNull()
  }
  升级后
  @sql.SqlInsert('replace into db_user (id,name,time,timeS) values (#{id},#{name},#{time},#{timeS})')
  insert(@sql.Param('id') id: number, @sql.Param('name') name: string, @sql.Param('time') time: string,
    @sql.Param('timeS') timeS: number): Promise<void> {
    return sql.PromiseNull()
  }
  报错
  Config[Log]: Error(1) errno is:22 table db_user has no column named time in "replace into db_user (id,name,time,timeS) values (?,?,?,?)".

**Comment by liushengyi** [comment]
需要自己处理 列的添加删除，eg:  ALTER TABLE db_user ADD COLUMN time  text
