### ISSUE TITLE
请问SQL语句查询 limit支持吗？

### ISSUE THREAD

**Issue by Punishing** [liushengyi/smartdb#27]
查询日志如下：
MessageContentDao.queryMessageContentByRoomId sql: select * from im_message_content_list where room_id=? LIMIT 20 bindArgs: 6657ddb201118771390135b2

目前可以确认"select * from im_message_content_list  ORDER BY send_time DESC”查询能查询出所有数据，但是加上条件查询
where room_id=? LIMIT 20 bindArgs: 6657ddb201118771390135b2
只能取到一条数据，可以确认的是room_id：6657ddb201118771390135b2 不止一条数据，能帮我看看问题在哪吗？

**Comment by Punishing** [comment]
这是我创建语句  

@sql.Sql("create table if not exists " + MessageContentDao.TABLE_NAME +
    "(message_id TEXT PRIMARY KEY" +
    ",message_type TEXT" +
    ",content_type TEXT" +
    ",content_json TEXT" +
    ",room_id TEXT" +
    ",from_uid TEXT" +
    ",to_uid TEXT" +
    ",from_name TEXT" +
    ",from_avatar TEXT" +
    ",from_medal TEXT" +
    ",from_level TEXT" +
    ",from_medal_title TEXT" +
    ",recall_uid TEXT" +
    ",recall_operator TEXT" +
    ",extra TEXT" +
    ",is_self INTEGER" +
    ",create_time INTEGER" +
    ",send_time INTEGER" +
    ")")

**Comment by Punishing** [comment]
我查询所有数据可以确认的是room_id：6657ddb201118771390135b2 不止一条数据
![image](https://github.com/user-attachments/assets/951d515e-442d-4034-8bb7-b6acb975bdc5)

**Comment by liushengyi** [comment]
https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-data-rdb-V5#querysql8
可以直接用官方querySql接口 测试，是否有同样问题。
smartdb只是封装了sql拼接，没有修改sql特性，limit 肯定是支持的。

**Comment by Punishing** [comment]
可以的。我sql那边写错没返回数组。不好意思我这边的问题  @sql.ReturnType([MessageContentDO])，漏写了 []
