### ISSUE TITLE
将DAO 文件移植到lib中，module中做数据库处理，一直不行 好像是参数问题

### ISSUE THREAD

**Issue by lovehua** [liushengyi/smartdb#29]
NapiRdbJsUtils[Convert2Value]: test (status == napi_ok) failed: get stageMode param failed
09-13 11:10:48.982   32645-32645   C01650/Rdb                      com.zkzy.v0           E     AsyncCall[SetAction]: throw error: code = 401 , message = Parameter error.Illegal context.
09-13 11:10:48.983   32645-32645   A0ff00/smartdb                  com.zkzy.v0           E     Parameter error.Illegal context.     at anonymous (librarys/lib_smartdb/src/main/ets/DbHelper.ts:66:9)
09-13 11:10:48.983   32645-32645   A0ff00/smartdb                  com.zkzy.v0           E         at getRdbStore (librarys/lib_smartdb/src/main/ets/DbHelper.ts:62:12)
09-13 11:10:48.983   32645-32645   A0ff00/smartdb                  com.zkzy.v0           E         at anonymous (librarys/lib_smartdb/src/main/ets/annotation/SqlQuery.ts:9:30)
09-13 11:10:48.983   32645-32645   A0ff00/smartdb                  com.zkzy.v0           E         at anonymous (librarys/lib_smartdb/src/main/ets/annotation/SqlQuery.ts:6:12)
09-13 11:10:48.983   32645-32645   A0ff00/smartdb                  com.zkzy.v0           E         at anonymous (librarys/lib_smartdb/src/main/ets/DbUtil.ts:68:16)
09-13 11:10:48.983   32645-32645   A0ff00/smartdb                  com.zkzy.v0           E         at getCaiJiSystem (modules/module_login/src/main/ets/pages/Index.ets:31:5)
09-13 11:10:48.983   32645-32645   A0ff00/smartdb                  com.zkzy.v0           E         at anonymous (modules/module_login/src/main/ets/pages/Index.ets:16:13)

**Comment by liushengyi** [comment]
不明白你所说的移植是什么意思。 从日志看，context 传递错误了。
