### ISSUE TITLE
把入库耗时操作放到taskpool线程池中执行，报错了

### ISSUE THREAD

**Issue by JimmyMo2** [liushengyi/smartdb#30]
![image](https://github.com/user-attachments/assets/cb30fc4b-2b00-4527-a059-d8429d5e53f4)

**Comment by liushengyi** [comment]
确认下context是否传递正确。

**Comment by JimmyMo2** [comment]
> 确认下context是否传递正确。

就工程入口初始化传了context，数据入库传不了啊，没有提供相关参数来传
![image](https://github.com/user-attachments/assets/08ebe852-1aa8-4229-a375-dc19b34210d8)

**Comment by liushengyi** [comment]
taskpool线程和主线程是隔离的，内存不共享，这里context实际是null的。task里需要单独在初始化 db.

**Comment by JimmyMo2** [comment]
> taskpool线程和主线程是隔离的，内存不共享，这里context实际是null的。task里需要单独在初始化 db.
好的，我先试试
for循环入库会有问题，每次for循环都会执行下连接和close方法，所以造成了卡顿，这也是为啥要我将入库操作放进taskpool的原因，但这里设计感觉有点问题，除非是这个api不建议使用来for循环来批量插入数据
![image](https://github.com/user-attachments/assets/bab7859d-4d25-4072-b73a-c2933aa5164c)

**Comment by liushengyi** [comment]
close的是 ResultSet，并不是rdbStore.
不知道，你所指的卡顿是指什么，可以提供下demo.

**Comment by JimmyMo2** [comment]
> close的是 ResultSet，并不是rdbStore. 不知道，你所指的卡顿是指什么，可以提供下demo.


![image](https://github.com/user-attachments/assets/7bc1f96f-9e33-43a2-aff0-1cc4cac950b2)
省、市、区 数据加起来3600多条左右，分别for循环将数据入库，会阻塞UI主线程，冷启动app，页面渲染会受影响

**Comment by liushengyi** [comment]
1 批量插入，建议自己拼接sql, 使用自定义条件一次性插入
2 数据库操作都是异步的，是不会堵塞主线程的

**Comment by JimmyMo2** [comment]
> > taskpool线程和主线程是隔离的，内存不共享，这里context实际是null的。task里需要单独在初始化 db.
> > 好的，我先试试
> > for循环入库会有问题，每次for循环都会执行下连接和close方法，所以造成了卡顿，这也是为啥要我将入库操作放进taskpool的原因，但这里设计感觉有点问题，除非是这个api不建议使用来for循环来批量插入数据
> > ![image](https://private-user-images.githubusercontent.com/32846008/367503007-bab7859d-4d25-4072-b73a-c2933aa5164c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDQ3NjIsIm5iZiI6MTcyNjMwNDQ2MiwicGF0aCI6Ii8zMjg0NjAwOC8zNjc1MDMwMDctYmFiNzg1OWQtNGQyNS00MDcyLWI3M2EtYzI5MzNhYTUxNjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA5MDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NTRiZjE1ZDdhNjNhNDQ1ZDFiOTg0OWVlYTVhZTdkYzY5NWFlNWZlMTQ1MDNmOGMyNTYzNWFjNTU3NzA5Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bgpOsQnkCp--zqKWvnopWX5mok2rlCAZeV3azaQe8ng)


试了，taskpool中传入context初始化可行

**Comment by JimmyMo2** [comment]
> 1 批量插入，建议自己拼接sql, 使用自定义条件一次性插入 2 数据库操作都是异步的，是不会堵塞主线程的

自定义拼接sql来批量插入，该方案应该最佳。
之前for循环插入也是异步的，不知道咋回事，就是阻塞了ui线程

**Comment by JimmyMo2** [comment]
> close的是 ResultSet，并不是rdbStore. 不知道，你所指的卡顿是指什么，可以提供下demo.



> 1 批量插入，建议自己拼接sql, 使用自定义条件一次性插入 2 数据库操作都是异步的，是不会堵塞主线程的

使用自定义条件自己拼接sql，批量插入失败了，请问哪里有问题呢
<img width="1199" alt="image" src="https://github.com/user-attachments/assets/aea4ac06-9b70-4830-8222-307e157767d3">
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/0aaa8374-a5ea-4c61-9f62-7179be8636b6">

**Comment by Punishing** [comment]
@JimmyMo2 你好。我目前也是跟你一样碰到这个 for 循环插入卡顿问题。。请问你批量插入的sql语句是怎么写的？
