### ISSUE TITLE
插入数据失败？

### ISSUE THREAD

**Issue by liuhuanzhu-git** [liushengyi/smartdb#31]
当前环境是DevEco Studio NEXT Beta1
API版本是12
按照文档中的例子去实现代码，用模拟器启动应用，插入数据的时候显示插入失败。
请问有其他设置的地方吗？

![1726297041948](https://github.com/user-attachments/assets/8ac7faba-cf1e-4530-bebc-e7f074095d83)

![WX20240914-150025](https://github.com/user-attachments/assets/dd033b06-692e-4f03-a69f-b6aa990fc366)

**Comment by liushengyi** [comment]
这里 throw 异常，只是为了测试事务回滚。

**Comment by liuhuanzhu-git** [comment]
> 这里 throw 异常，只是为了测试事务回滚。

我的错没注意这个是自己抛出来的逻辑，谢谢谢谢
