### ISSUE TITLE
请问对blob的支持如何？

### ISSUE THREAD

**Issue by xymeng16** [liushengyi/smartdb#32]
插入blob（对应ts类型为UInt8Array）时需要在sql语句进行任何标注或者转义等操作吗？

**Comment by liushengyi** [comment]
应该是不需要的。

**Comment by xymeng16** [comment]
> 应该是不需要的。

测试后会有问题，看错误信息里，应该是会直接将UInt8Array当做字符串处理，也就是说SQL语句会变成类似"INSERT INTO TABLE VALUES [1, 2, 3]"的形式。

请问有对blob类型插入和查询的例子么？

**Comment by liushengyi** [comment]
https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-data-relationalstore-V5#executesql
你可以用这个测试，是否是官方接口问题，smartdb 没有转换数据。

**Comment by xymeng16** [comment]
> https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-data-relationalstore-V5#executesql 你可以用这个测试，是否是官方接口问题，smartdb 没有转换数据。

既然没有转换数据，那就是官方的问题了，因为我之前用官方接口自己封装的对blob的插入也有相同的问题。

**Comment by liushengyi** [comment]
先关闭了
