### ISSUE TITLE
能否提供自定义转换功能

### ISSUE THREAD

**Issue by udoubi** [liushengyi/smartdb#34]
<img width="600" alt="image" src="https://github.com/user-attachments/assets/9b525425-6584-4768-b7fb-1ad070228210">
希望存入数据库的时候是字符串，取出来的时候是对象，可以在中间加一个自定义转换功能吗

**Comment by liushengyi** [comment]
这个，你在对象中实现一个方法就可以了。 eg: getChatMsg() . 集成 到smartdb 反而复杂了。
