### ISSUE TITLE
不支持API 11星河版本吗

### ISSUE THREAD

**Issue by w-q666** [liushengyi/smartdb#4]

**Comment by liushengyi** [comment]
是出现什么问题了？提供下更详细信息。

**Comment by w-q666** [comment]
抱歉我操作失误




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liushengyi/smartdb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月14日(星期二) 上午9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liushengyi/smartdb] 不支持API 11星河版本吗 (Issue #4)





 
是出现什么问题了？提供下更详细信息。
