### ISSUE TITLE
批量插入

### ISSUE THREAD

**Issue by Christain** [liushengyi/smartdb#41]
请问下批量插入的语句要怎么写？，我用for循环拼接了一个string，放到@sql.SqlInsert(#{string}），识别不到。能写个简单的示例吗？

**Comment by liushengyi** [comment]
贴下你代码。

**Comment by Christain** [comment]
![微信截图_20241115092602](https://github.com/user-attachments/assets/d5ce4d7c-2416-408f-bcd5-2150809ac402)

**Comment by liushengyi** [comment]
demo 里对应的就是测试用例。截图下你日志。
```
 Button("自定义条件拼接").onClick(() => {
          userDao.searchUser(" name like 'id%'").then((result) => {
            sql.Logger.info(JSON.stringify(result))
          })
        })
```

**Comment by Christain** [comment]
![微信截图_20241115095759](https://github.com/user-attachments/assets/b33b192a-3604-4eb0-a261-73b2e508f080)
![微信截图_20241115095835](https://github.com/user-attachments/assets/bf3564b1-b7a1-4903-ac1f-1e44983f2d36)
传进去的sql语句和报错信息。麻烦帮忙在看一下，谢谢

**Comment by Christain** [comment]
![image](https://github.com/user-attachments/assets/f83d4921-7376-4b21-a580-d688344cb5d7)
拼接的sql是完整的，您封装的方法里bindArgs是必传的，不知道是不是这原因造成的

**Comment by liushengyi** [comment]
字符串类型的参数，拼接时需要添加 引号 。 eg:  menuName

**Comment by Christain** [comment]
谢谢，可以了。就是拼接没有加引号的问题
