### ISSUE TITLE
#{t.openid} 如果对象属性openid为空，报错

### ISSUE THREAD

**Issue by w-q666** [liushengyi/smartdb#5]
就是在写插入sql的时候（json转换，一般arkTS不允许为空）对象属性为空，#{t.openid} 对象属性openid为空，报错

**Comment by w-q666** [comment]
已经验证报内部错误，不方便截图，可复现

**Comment by liushengyi** [comment]
定义对象，最好给默认值(字符类型：“”)，而不是给null或者undefine

**Comment by w-q666** [comment]
ArkTS限制空值了，但是这网络传输 json转对象 确有空值

**Comment by w-q666** [comment]
好的
