### ISSUE TITLE
写sql时如果某个参数被多处引用，会有问题

### ISSUE THREAD

**Issue by YZune** [liushengyi/smartdb#6]
如题，查看源码发现是因为`newSql.replace`只会进行一次替换，应该改成全部替换？
<img width="763" alt="image" src="https://github.com/liushengyi/smartdb/assets/22848999/8805e4ab-71ef-404c-8d94-51568a2de6b5">

**Comment by liushengyi** [comment]
好的，我修复下

**Comment by liushengyi** [comment]
新版本2.0.1更新了。
