### ISSUE TITLE
not select sql !

### ISSUE THREAD

**Issue by w-q666** [liushengyi/smartdb#7]
05-30 09:15:48.140   5925-5925    C01650/Rdb                     pid-5925              E     [nodict]::[PrepareStep()-sqlite_shared_result_set.cpp:42]: StoreSession BeginStepQuery fail : not select sql !

**Comment by liushengyi** [comment]
发下具体错误

**Comment by w-q666** [comment]
没问题了，ArkTs编译器问题，清理项目重新编译又好了
