### ISSUE TITLE
该库内部核心对象如DbHelper是单例、只支持同时一个DB

### ISSUE THREAD

**Issue by chenranok** [liushengyi/smartdb#9]
该库内部核心对象如DbHelper是单例，以至只能有一个DB，
需要扩展消除单例，能支持同时有好几个想到独立的DB；

**Comment by liushengyi** [comment]
这个有考虑，下个版本考虑支持。

**Comment by chenranok** [comment]
谢谢兄弟哦，项目就等着续命了；
那些装饰反射完全看不懂，要不就一块干了

**Comment by zhengchengrong** [comment]
是不支持创建多个库吗，比如每个用户对应一个数据库，分库分表

**Comment by chenranok** [comment]
> 是不支持创建多个库吗，比如每个用户对应一个数据库，分库分表
是的， 目前只能是一个库；内部实现几个节点对象均采用单例。

**Comment by liushengyi** [comment]
3.0.0版本已经发布，支持多数据源。 预计明天后天可以审核通过。目前如果急用，可以下载源码依赖。

**Comment by chenranok** [comment]
同时支持，允许一个应用有多个  DATABASE 那真是太棒了；SQL是锁库的，多个库效能高；
一个登录用户一个，  并且 几个超大表 各单独用一个

**Comment by liushengyi** [comment]
这个issue，先关闭了。
